package com.htcf.webService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "WebService_GetDataSoap", targetNamespace = "http://tempuri.org/")
public interface WebServiceGetDataSoap {

	/**
	 * 
	 * @param strBT
	 * @param strET
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetZSYF", action = "http://tempuri.org/GetZSYF")
	@WebResult(name = "GetZSYFResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetZSYF", targetNamespace = "http://tempuri.org/", className = "com.htcf.webService.GetZSYF")
	@ResponseWrapper(localName = "GetZSYFResponse", targetNamespace = "http://tempuri.org/", className = "com.htcf.webService.GetZSYFResponse")
	public String getZSYF(
			@WebParam(name = "strBT", targetNamespace = "http://tempuri.org/") String strBT,
			@WebParam(name = "strET", targetNamespace = "http://tempuri.org/") String strET);

	/**
	 * 
	 * @param strBT
	 * @param strET
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetZSTJ", action = "http://tempuri.org/GetZSTJ")
	@WebResult(name = "GetZSTJResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetZSTJ", targetNamespace = "http://tempuri.org/", className = "com.htcf.webService.GetZSTJ")
	@ResponseWrapper(localName = "GetZSTJResponse", targetNamespace = "http://tempuri.org/", className = "com.htcf.webService.GetZSTJResponse")
	public String getZSTJ(
			@WebParam(name = "strBT", targetNamespace = "http://tempuri.org/") String strBT,
			@WebParam(name = "strET", targetNamespace = "http://tempuri.org/") String strET);

	/**
	 * 
	 * @param strBT
	 * @param type
	 * @param strET
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetTJTab", action = "http://tempuri.org/GetTJTab")
	@WebResult(name = "GetTJTabResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetTJTab", targetNamespace = "http://tempuri.org/", className = "com.htcf.webService.GetTJTab")
	@ResponseWrapper(localName = "GetTJTabResponse", targetNamespace = "http://tempuri.org/", className = "com.htcf.webService.GetTJTabResponse")
	public String getTJTab(
			@WebParam(name = "strBT", targetNamespace = "http://tempuri.org/") String strBT,
			@WebParam(name = "strET", targetNamespace = "http://tempuri.org/") String strET,
			@WebParam(name = "type", targetNamespace = "http://tempuri.org/") String type);

	/**
	 * 
	 * @param strBT
	 * @param type
	 * @param strET
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetTJTabDetail", action = "http://tempuri.org/GetTJTabDetail")
	@WebResult(name = "GetTJTabDetailResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetTJTabDetail", targetNamespace = "http://tempuri.org/", className = "com.htcf.webService.GetTJTabDetail")
	@ResponseWrapper(localName = "GetTJTabDetailResponse", targetNamespace = "http://tempuri.org/", className = "com.htcf.webService.GetTJTabDetailResponse")
	public String getTJTabDetail(
			@WebParam(name = "strBT", targetNamespace = "http://tempuri.org/") String strBT,
			@WebParam(name = "strET", targetNamespace = "http://tempuri.org/") String strET,
			@WebParam(name = "type", targetNamespace = "http://tempuri.org/") String type);

	/**
	 * 
	 * @param strBT
	 * @param name
	 * @param strET
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetWGHPatrolTrack", action = "http://tempuri.org/GetWGHPatrolTrack")
	@WebResult(name = "GetWGHPatrolTrackResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetWGHPatrolTrack", targetNamespace = "http://tempuri.org/", className = "com.htcf.webService.GetWGHPatrolTrack")
	@ResponseWrapper(localName = "GetWGHPatrolTrackResponse", targetNamespace = "http://tempuri.org/", className = "com.htcf.webService.GetWGHPatrolTrackResponse")
	public String getWGHPatrolTrack(
			@WebParam(name = "strBT", targetNamespace = "http://tempuri.org/") String strBT,
			@WebParam(name = "strET", targetNamespace = "http://tempuri.org/") String strET,
			@WebParam(name = "name", targetNamespace = "http://tempuri.org/") String name);

	/**
	 * 
	 * @param rwh
	 * @param strBT
	 * @param xl
	 * @param dl
	 * @param qx
	 * @param strET
	 * @param sj
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "GetWGHEvent", action = "http://tempuri.org/GetWGHEvent")
	@WebResult(name = "GetWGHEventResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "GetWGHEvent", targetNamespace = "http://tempuri.org/", className = "com.htcf.webService.GetWGHEvent")
	@ResponseWrapper(localName = "GetWGHEventResponse", targetNamespace = "http://tempuri.org/", className = "com.htcf.webService.GetWGHEventResponse")
	public String getWGHEvent(
			@WebParam(name = "strBT", targetNamespace = "http://tempuri.org/") String strBT,
			@WebParam(name = "strET", targetNamespace = "http://tempuri.org/") String strET,
			@WebParam(name = "sj", targetNamespace = "http://tempuri.org/") String sj,
			@WebParam(name = "qx", targetNamespace = "http://tempuri.org/") String qx,
			@WebParam(name = "dl", targetNamespace = "http://tempuri.org/") String dl,
			@WebParam(name = "xl", targetNamespace = "http://tempuri.org/") String xl,
			@WebParam(name = "rwh", targetNamespace = "http://tempuri.org/") String rwh);

}
