package com.htcf.webService;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * WebService_GetData service = new WebService_GetData();
 * WebServiceGetDataSoap portType = service.getWebServiceGetDataSoap();
 * portType.getZSYF(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "WebService_GetData", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://31.16.10.160/WGHS/WebService_GetData.asmx?wsdl")
public class WebServiceGetData extends Service {

	private final static URL WEBSERVICEGETDATA_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.htcf.webService.WebServiceGetData.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.htcf.webService.WebServiceGetData.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://31.16.10.160/WGHS/WebService_GetData.asmx?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://31.16.10.160/WGHS/WebService_GetData.asmx?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		WEBSERVICEGETDATA_WSDL_LOCATION = url;
	}

	public WebServiceGetData(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public WebServiceGetData() {
		super(WEBSERVICEGETDATA_WSDL_LOCATION, new QName("http://tempuri.org/",
				"WebService_GetData"));
	}

	/**
	 * 
	 * @return returns WebServiceGetDataSoap
	 */
	@WebEndpoint(name = "WebService_GetDataSoap")
	public WebServiceGetDataSoap getWebServiceGetDataSoap() {
		return super.getPort(new QName("http://tempuri.org/",
				"WebService_GetDataSoap"), WebServiceGetDataSoap.class);
	}

	/**
	 * 
	 * @return returns WebServiceGetDataSoap
	 */
	@WebEndpoint(name = "WebService_GetDataSoap12")
	public WebServiceGetDataSoap getWebServiceGetDataSoap12() {
		return super.getPort(new QName("http://tempuri.org/",
				"WebService_GetDataSoap12"), WebServiceGetDataSoap.class);
	}

}
